### ISSUE TITLE
Is this code actively maintained?

### ISSUE THREAD

**Issue by strypey** [jaromil/HasciiCam#3]
Ever since I first heard of HasciiCam, I though it was a genius idea. It continues to blow my mind that none of the free code video chat or video conferencing tools have made use of it to provide a light alternative for people on older computers or slower net connections.

I'm just wondering if this code is being actively maintained. Does the repo here provide a complete, usable application, or just a set of libraries that need to be combined with other software to build one? If it is a usable application, do you know if it's possible to use it on Trisquel, and where I could find installation instructions for that? Thanks heaps.

**Comment by jaromil** [comment]
hi. Yes is usable and I'm maintaining it (doesn't require much effort). Last fixes were to support wider range of cameras using YUV instead of RGB captures. I'm not aware of other needs ATM.
FYI there is an exhibition on history of digital art in Rome right now exhibiting Hasciicam in an installation http://binart.eu
